### ISSUE TITLE
[SELinux and Docker Volumes] flask.cli.NoAppException

### ISSUE THREAD

**Issue by Miikiele** [aleskandro/distributed-computing-exercises#7]
After cloning the repository and launching docker-compose up on the Docker-compose project CounterRedisPython, requests to localhost:8080 reply with: 

> flask.cli.NoAppException: Could not import "counter". 

## Steps to reproduce the issue
```sh
cd CounterRedisPython/
docker-compose up
curl http://localhost:8080
```
## System informations
Platform: Fedora 30 ; Docker version: 1.13 ; docker-compose version: 1.24.0

## Temporary solution

As root:
```sh
setenforce 0   # it switches off selinux policy
```

From CounterRedisPython:
```sh
docker-compose up
```

**Comment by aleskandro** [comment]
Hi, the issue is related to SELinux policies. With SELinux enabled and not properly configured you have not permissions on bound volumes.

The temporary solution you suggest is absolutely perfect if you aren't interested in SELinux policies. Essentially, it disables at all SELinux, until you reboot your system.

### Permanently disable SELinux

To make the solution permanent, as root:

```sh
sed -i /etc/selinux/config -e "s/^SELINUX=.*/SELINUX=disabled/"
``` 


### Achieving SELinux policies with Docker volumes and docker-compose (not tested)

However, if you want to keep SELinux enabled you should configure them.

Use the following links as reference:

- https://prefetch.net/blog/2017/09/30/using-docker-volumes-on-selinux-enabled-servers/
- https://www.projectatomic.io/blog/2015/06/using-volumes-with-docker-can-cause-problems-with-selinux/
- tomav/docker-mailserver#753
